[server]
port = 8888
mpv_pipe = \\.\pipe\mpv-music-server
admin_password = admin
max_duration_minutes = 10

[paths]
; You can use absolute path or command name in PATH.
; Example:
; mpv_path = D:\python\MusicServer\mpv.exe
; ytdlp_path = D:\python\MusicServer\yt-dlp.exe
; ytdlp_cmd = yt-dlp
; ytdlp_cmd can be a full shell command. If set, it is used instead of ytdlp_path.
mpv_path = D:\python\MusicServer\mpv.exe
ytdlp_path = D:\python\MusicServer\yt-dlp.exe
ytdlp_cmd = D:\python\MusicServer\yt-dlp.exe

